{% set name = "codecov" %}
{% set version = "2.0.22" %}
{% set sha256 = "4a1e97dd339988e29536b56f2da31bed8a628cf12bb920a0d545820cf111b8fa" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # Not on pypi (at time of packaging)
  url: https://github.com/codecov/codecov-python/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - codecov=codecov:main

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - coverage
    - requests >=2.7.9

test:
  imports:
    - codecov
  commands:
    - codecov -h

about:
  home: https://github.com/codecov/codecov-python
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Hosted coverage reports for Github, Bitbucket and Gitlab
  doc_url: https://github.com/codecov/codecov-python
  dev_url: https://github.com/codecov/codecov-python

extra:
  recipe-maintainers:
    - CJ-Wright
